// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.16.0
// source: op.proto

package patch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpClear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *OpClear) Reset() {
	*x = OpClear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpClear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpClear) ProtoMessage() {}

func (x *OpClear) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpClear.ProtoReflect.Descriptor instead.
func (*OpClear) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{0}
}

func (x *OpClear) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OpDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *OpDel) Reset() {
	*x = OpDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpDel) ProtoMessage() {}

func (x *OpDel) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpDel.ProtoReflect.Descriptor instead.
func (*OpDel) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{1}
}

func (x *OpDel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OpExpire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Expiration int64  `protobuf:"varint,2,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (x *OpExpire) Reset() {
	*x = OpExpire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpExpire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpExpire) ProtoMessage() {}

func (x *OpExpire) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpExpire.ProtoReflect.Descriptor instead.
func (*OpExpire) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{2}
}

func (x *OpExpire) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpExpire) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type OpExpireAt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Expiration int64  `protobuf:"varint,2,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (x *OpExpireAt) Reset() {
	*x = OpExpireAt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpExpireAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpExpireAt) ProtoMessage() {}

func (x *OpExpireAt) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpExpireAt.ProtoReflect.Descriptor instead.
func (*OpExpireAt) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{3}
}

func (x *OpExpireAt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpExpireAt) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type OpHClear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *OpHClear) Reset() {
	*x = OpHClear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHClear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHClear) ProtoMessage() {}

func (x *OpHClear) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHClear.ProtoReflect.Descriptor instead.
func (*OpHClear) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{4}
}

func (x *OpHClear) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OpHDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Fields []string `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
}

func (x *OpHDel) Reset() {
	*x = OpHDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHDel) ProtoMessage() {}

func (x *OpHDel) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHDel.ProtoReflect.Descriptor instead.
func (*OpHDel) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{5}
}

func (x *OpHDel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpHDel) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type OpHIncrBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Field   string `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	IncrInt int64  `protobuf:"varint,3,opt,name=IncrInt,proto3" json:"IncrInt,omitempty"`
}

func (x *OpHIncrBy) Reset() {
	*x = OpHIncrBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHIncrBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHIncrBy) ProtoMessage() {}

func (x *OpHIncrBy) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHIncrBy.ProtoReflect.Descriptor instead.
func (*OpHIncrBy) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{6}
}

func (x *OpHIncrBy) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpHIncrBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OpHIncrBy) GetIncrInt() int64 {
	if x != nil {
		return x.IncrInt
	}
	return 0
}

type OpHIncrByFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Field     string  `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	IncrFloat float64 `protobuf:"fixed64,3,opt,name=IncrFloat,proto3" json:"IncrFloat,omitempty"`
}

func (x *OpHIncrByFloat) Reset() {
	*x = OpHIncrByFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHIncrByFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHIncrByFloat) ProtoMessage() {}

func (x *OpHIncrByFloat) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHIncrByFloat.ProtoReflect.Descriptor instead.
func (*OpHIncrByFloat) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{7}
}

func (x *OpHIncrByFloat) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpHIncrByFloat) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OpHIncrByFloat) GetIncrFloat() float64 {
	if x != nil {
		return x.IncrFloat
	}
	return 0
}

type OpHSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *OpHSet) Reset() {
	*x = OpHSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHSet) ProtoMessage() {}

func (x *OpHSet) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHSet.ProtoReflect.Descriptor instead.
func (*OpHSet) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{8}
}

func (x *OpHSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpHSet) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OpHSet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OpHMSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Fields []string `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Values [][]byte `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *OpHMSet) Reset() {
	*x = OpHMSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpHMSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpHMSet) ProtoMessage() {}

func (x *OpHMSet) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpHMSet.ProtoReflect.Descriptor instead.
func (*OpHMSet) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{9}
}

func (x *OpHMSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpHMSet) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *OpHMSet) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type OpLInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Pivot  []byte `protobuf:"bytes,2,opt,name=Pivot,proto3" json:"Pivot,omitempty"`
	Value  []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Before bool   `protobuf:"varint,4,opt,name=Before,proto3" json:"Before,omitempty"`
}

func (x *OpLInsert) Reset() {
	*x = OpLInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLInsert) ProtoMessage() {}

func (x *OpLInsert) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLInsert.ProtoReflect.Descriptor instead.
func (*OpLInsert) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{10}
}

func (x *OpLInsert) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLInsert) GetPivot() []byte {
	if x != nil {
		return x.Pivot
	}
	return nil
}

func (x *OpLInsert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OpLInsert) GetBefore() bool {
	if x != nil {
		return x.Before
	}
	return false
}

type OpLPop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *OpLPop) Reset() {
	*x = OpLPop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLPop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLPop) ProtoMessage() {}

func (x *OpLPop) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLPop.ProtoReflect.Descriptor instead.
func (*OpLPop) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{11}
}

func (x *OpLPop) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLPop) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OpLPopRPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	DstKey string `protobuf:"bytes,2,opt,name=DstKey,proto3" json:"DstKey,omitempty"`
}

func (x *OpLPopRPush) Reset() {
	*x = OpLPopRPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLPopRPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLPopRPush) ProtoMessage() {}

func (x *OpLPopRPush) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLPopRPush.ProtoReflect.Descriptor instead.
func (*OpLPopRPush) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{12}
}

func (x *OpLPopRPush) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLPopRPush) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

type OpLPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *OpLPush) Reset() {
	*x = OpLPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLPush) ProtoMessage() {}

func (x *OpLPush) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLPush.ProtoReflect.Descriptor instead.
func (*OpLPush) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{13}
}

func (x *OpLPush) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLPush) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type OpLPushX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *OpLPushX) Reset() {
	*x = OpLPushX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLPushX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLPushX) ProtoMessage() {}

func (x *OpLPushX) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLPushX.ProtoReflect.Descriptor instead.
func (*OpLPushX) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{14}
}

func (x *OpLPushX) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLPushX) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OpLRem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Count int64  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *OpLRem) Reset() {
	*x = OpLRem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLRem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLRem) ProtoMessage() {}

func (x *OpLRem) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLRem.ProtoReflect.Descriptor instead.
func (*OpLRem) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{15}
}

func (x *OpLRem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLRem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OpLRem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OpLSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Index int64  `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *OpLSet) Reset() {
	*x = OpLSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLSet) ProtoMessage() {}

func (x *OpLSet) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLSet.ProtoReflect.Descriptor instead.
func (*OpLSet) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{16}
}

func (x *OpLSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLSet) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OpLSet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OpLTrim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Stop  int64  `protobuf:"varint,3,opt,name=Stop,proto3" json:"Stop,omitempty"`
}

func (x *OpLTrim) Reset() {
	*x = OpLTrim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLTrim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLTrim) ProtoMessage() {}

func (x *OpLTrim) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLTrim.ProtoReflect.Descriptor instead.
func (*OpLTrim) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{17}
}

func (x *OpLTrim) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpLTrim) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *OpLTrim) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type OpRPop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *OpRPop) Reset() {
	*x = OpRPop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRPop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRPop) ProtoMessage() {}

func (x *OpRPop) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRPop.ProtoReflect.Descriptor instead.
func (*OpRPop) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{18}
}

func (x *OpRPop) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRPop) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OpRPopLPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	DstKey string `protobuf:"bytes,2,opt,name=DstKey,proto3" json:"DstKey,omitempty"`
}

func (x *OpRPopLPush) Reset() {
	*x = OpRPopLPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRPopLPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRPopLPush) ProtoMessage() {}

func (x *OpRPopLPush) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRPopLPush.ProtoReflect.Descriptor instead.
func (*OpRPopLPush) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{19}
}

func (x *OpRPopLPush) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRPopLPush) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

type OpRPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *OpRPush) Reset() {
	*x = OpRPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRPush) ProtoMessage() {}

func (x *OpRPush) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRPush.ProtoReflect.Descriptor instead.
func (*OpRPush) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{20}
}

func (x *OpRPush) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRPush) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type OpRPushX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *OpRPushX) Reset() {
	*x = OpRPushX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRPushX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRPushX) ProtoMessage() {}

func (x *OpRPushX) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRPushX.ProtoReflect.Descriptor instead.
func (*OpRPushX) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{21}
}

func (x *OpRPushX) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRPushX) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OpSAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *OpSAdd) Reset() {
	*x = OpSAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpSAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpSAdd) ProtoMessage() {}

func (x *OpSAdd) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpSAdd.ProtoReflect.Descriptor instead.
func (*OpSAdd) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{22}
}

func (x *OpSAdd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpSAdd) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type OpSRem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *OpSRem) Reset() {
	*x = OpSRem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpSRem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpSRem) ProtoMessage() {}

func (x *OpSRem) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpSRem.ProtoReflect.Descriptor instead.
func (*OpSRem) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{23}
}

func (x *OpSRem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpSRem) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type OpSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value      []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	KeepTTL    bool   `protobuf:"varint,3,opt,name=KeepTTL,proto3" json:"KeepTTL,omitempty"`
	Expiration int64  `protobuf:"varint,4,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (x *OpSet) Reset() {
	*x = OpSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpSet) ProtoMessage() {}

func (x *OpSet) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpSet.ProtoReflect.Descriptor instead.
func (*OpSet) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{24}
}

func (x *OpSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpSet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OpSet) GetKeepTTL() bool {
	if x != nil {
		return x.KeepTTL
	}
	return false
}

func (x *OpSet) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type OpZAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Member string  `protobuf:"bytes,2,opt,name=Member,proto3" json:"Member,omitempty"`
	Score  float64 `protobuf:"fixed64,3,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *OpZAdd) Reset() {
	*x = OpZAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZAdd) ProtoMessage() {}

func (x *OpZAdd) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZAdd.ProtoReflect.Descriptor instead.
func (*OpZAdd) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{25}
}

func (x *OpZAdd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZAdd) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *OpZAdd) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type OpZClear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *OpZClear) Reset() {
	*x = OpZClear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZClear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZClear) ProtoMessage() {}

func (x *OpZClear) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZClear.ProtoReflect.Descriptor instead.
func (*OpZClear) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{26}
}

func (x *OpZClear) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OpZIncrBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Member string  `protobuf:"bytes,2,opt,name=Member,proto3" json:"Member,omitempty"`
	Score  float64 `protobuf:"fixed64,3,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *OpZIncrBy) Reset() {
	*x = OpZIncrBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZIncrBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZIncrBy) ProtoMessage() {}

func (x *OpZIncrBy) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZIncrBy.ProtoReflect.Descriptor instead.
func (*OpZIncrBy) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{27}
}

func (x *OpZIncrBy) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZIncrBy) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *OpZIncrBy) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type OpZRem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Member  string   `protobuf:"bytes,2,opt,name=Member,proto3" json:"Member,omitempty"`
	Members []string `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *OpZRem) Reset() {
	*x = OpZRem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZRem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZRem) ProtoMessage() {}

func (x *OpZRem) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZRem.ProtoReflect.Descriptor instead.
func (*OpZRem) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{28}
}

func (x *OpZRem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZRem) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *OpZRem) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type OpZRemRangeByRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Stop  int64  `protobuf:"varint,3,opt,name=Stop,proto3" json:"Stop,omitempty"`
}

func (x *OpZRemRangeByRank) Reset() {
	*x = OpZRemRangeByRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZRemRangeByRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZRemRangeByRank) ProtoMessage() {}

func (x *OpZRemRangeByRank) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZRemRangeByRank.ProtoReflect.Descriptor instead.
func (*OpZRemRangeByRank) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{29}
}

func (x *OpZRemRangeByRank) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZRemRangeByRank) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *OpZRemRangeByRank) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type OpZRemRangeByScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Mode int64   `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Min  float64 `protobuf:"fixed64,3,opt,name=Min,proto3" json:"Min,omitempty"`
	Max  float64 `protobuf:"fixed64,4,opt,name=Max,proto3" json:"Max,omitempty"`
}

func (x *OpZRemRangeByScore) Reset() {
	*x = OpZRemRangeByScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZRemRangeByScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZRemRangeByScore) ProtoMessage() {}

func (x *OpZRemRangeByScore) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZRemRangeByScore.ProtoReflect.Descriptor instead.
func (*OpZRemRangeByScore) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{30}
}

func (x *OpZRemRangeByScore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZRemRangeByScore) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *OpZRemRangeByScore) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *OpZRemRangeByScore) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type OpRename struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	DstKey string `protobuf:"bytes,2,opt,name=DstKey,proto3" json:"DstKey,omitempty"`
}

func (x *OpRename) Reset() {
	*x = OpRename{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRename) ProtoMessage() {}

func (x *OpRename) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRename.ProtoReflect.Descriptor instead.
func (*OpRename) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{31}
}

func (x *OpRename) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRename) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

type OpPersist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *OpPersist) Reset() {
	*x = OpPersist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpPersist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpPersist) ProtoMessage() {}

func (x *OpPersist) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpPersist.ProtoReflect.Descriptor instead.
func (*OpPersist) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{32}
}

func (x *OpPersist) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OpZUnionStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Keys      []string  `protobuf:"bytes,2,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Weights   []float64 `protobuf:"fixed64,3,rep,packed,name=Weights,proto3" json:"Weights,omitempty"`
	Aggregate string    `protobuf:"bytes,4,opt,name=Aggregate,proto3" json:"Aggregate,omitempty"`
}

func (x *OpZUnionStore) Reset() {
	*x = OpZUnionStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZUnionStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZUnionStore) ProtoMessage() {}

func (x *OpZUnionStore) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZUnionStore.ProtoReflect.Descriptor instead.
func (*OpZUnionStore) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{33}
}

func (x *OpZUnionStore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZUnionStore) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *OpZUnionStore) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *OpZUnionStore) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

type OpZInterStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string    `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Keys      []string  `protobuf:"bytes,2,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Weights   []float64 `protobuf:"fixed64,3,rep,packed,name=Weights,proto3" json:"Weights,omitempty"`
	Aggregate string    `protobuf:"bytes,4,opt,name=Aggregate,proto3" json:"Aggregate,omitempty"`
}

func (x *OpZInterStore) Reset() {
	*x = OpZInterStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpZInterStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpZInterStore) ProtoMessage() {}

func (x *OpZInterStore) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpZInterStore.ProtoReflect.Descriptor instead.
func (*OpZInterStore) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{34}
}

func (x *OpZInterStore) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpZInterStore) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *OpZInterStore) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *OpZInterStore) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

type OpRenameNX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	DstKey string `protobuf:"bytes,2,opt,name=DstKey,proto3" json:"DstKey,omitempty"`
}

func (x *OpRenameNX) Reset() {
	*x = OpRenameNX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRenameNX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRenameNX) ProtoMessage() {}

func (x *OpRenameNX) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRenameNX.ProtoReflect.Descriptor instead.
func (*OpRenameNX) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{35}
}

func (x *OpRenameNX) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpRenameNX) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

var File_op_proto protoreflect.FileDescriptor

var file_op_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x1b, 0x0a, 0x07, 0x4f, 0x70, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x19,
	0x0a, 0x05, 0x4f, 0x70, 0x44, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x3c, 0x0a, 0x08, 0x4f, 0x70, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0a, 0x4f, 0x70, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x08, 0x4f, 0x70, 0x48, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x06, 0x4f, 0x70, 0x48, 0x44, 0x65, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x09, 0x4f, 0x70, 0x48,
	0x49, 0x6e, 0x63, 0x72, 0x42, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x6e, 0x63, 0x72, 0x49, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x49, 0x6e, 0x63, 0x72, 0x49, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x0e, 0x4f, 0x70, 0x48, 0x49,
	0x6e, 0x63, 0x72, 0x42, 0x79, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x63, 0x72, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x49, 0x6e, 0x63, 0x72, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x22, 0x46, 0x0a, 0x06, 0x4f, 0x70, 0x48, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x07, 0x4f, 0x70, 0x48, 0x4d,
	0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x09, 0x4f, 0x70, 0x4c, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x69, 0x76, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x69, 0x76, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x4f, 0x70, 0x4c, 0x50,
	0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0b, 0x4f, 0x70,
	0x4c, 0x50, 0x6f, 0x70, 0x52, 0x50, 0x75, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x73, 0x74,
	0x4b, 0x65, 0x79, 0x22, 0x33, 0x0a, 0x07, 0x4f, 0x70, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x08, 0x4f, 0x70, 0x4c, 0x50,
	0x75, 0x73, 0x68, 0x58, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x06,
	0x4f, 0x70, 0x4c, 0x52, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x06, 0x4f, 0x70, 0x4c, 0x53, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x45, 0x0a, 0x07,
	0x4f, 0x70, 0x4c, 0x54, 0x72, 0x69, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53,
	0x74, 0x6f, 0x70, 0x22, 0x30, 0x0a, 0x06, 0x4f, 0x70, 0x52, 0x50, 0x6f, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0b, 0x4f, 0x70, 0x52, 0x50, 0x6f, 0x70, 0x4c,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x33,
	0x0a, 0x07, 0x4f, 0x70, 0x52, 0x50, 0x75, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x08, 0x4f, 0x70, 0x52, 0x50, 0x75, 0x73, 0x68, 0x58, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x4f, 0x70, 0x53, 0x41, 0x64,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x34, 0x0a,
	0x06, 0x4f, 0x70, 0x53, 0x52, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x22, 0x69, 0x0a, 0x05, 0x4f, 0x70, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x65, 0x70, 0x54, 0x54, 0x4c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4b, 0x65, 0x65, 0x70, 0x54, 0x54, 0x4c, 0x12, 0x1e,
	0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x48,
	0x0a, 0x06, 0x4f, 0x70, 0x5a, 0x41, 0x64, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x4f, 0x70, 0x5a, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x4b, 0x0a, 0x09, 0x4f, 0x70, 0x5a, 0x49, 0x6e, 0x63,
	0x72, 0x42, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x4c, 0x0a, 0x06, 0x4f, 0x70, 0x5a, 0x52, 0x65, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x22, 0x4f, 0x0a, 0x11, 0x4f, 0x70, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x42, 0x79, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x74,
	0x6f, 0x70, 0x22, 0x5e, 0x0a, 0x12, 0x4f, 0x70, 0x5a, 0x52, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x42, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4d,
	0x61, 0x78, 0x22, 0x34, 0x0a, 0x08, 0x4f, 0x70, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x1d, 0x0a, 0x09, 0x4f, 0x70, 0x50, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x6d, 0x0a, 0x0d, 0x4f, 0x70, 0x5a, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x07, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x22, 0x6d, 0x0a, 0x0d, 0x4f, 0x70, 0x5a, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x79,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x0a, 0x4f, 0x70, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x4e, 0x58, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_op_proto_rawDescOnce sync.Once
	file_op_proto_rawDescData = file_op_proto_rawDesc
)

func file_op_proto_rawDescGZIP() []byte {
	file_op_proto_rawDescOnce.Do(func() {
		file_op_proto_rawDescData = protoimpl.X.CompressGZIP(file_op_proto_rawDescData)
	})
	return file_op_proto_rawDescData
}

var file_op_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_op_proto_goTypes = []any{
	(*OpClear)(nil),            // 0: patch.OpClear
	(*OpDel)(nil),              // 1: patch.OpDel
	(*OpExpire)(nil),           // 2: patch.OpExpire
	(*OpExpireAt)(nil),         // 3: patch.OpExpireAt
	(*OpHClear)(nil),           // 4: patch.OpHClear
	(*OpHDel)(nil),             // 5: patch.OpHDel
	(*OpHIncrBy)(nil),          // 6: patch.OpHIncrBy
	(*OpHIncrByFloat)(nil),     // 7: patch.OpHIncrByFloat
	(*OpHSet)(nil),             // 8: patch.OpHSet
	(*OpHMSet)(nil),            // 9: patch.OpHMSet
	(*OpLInsert)(nil),          // 10: patch.OpLInsert
	(*OpLPop)(nil),             // 11: patch.OpLPop
	(*OpLPopRPush)(nil),        // 12: patch.OpLPopRPush
	(*OpLPush)(nil),            // 13: patch.OpLPush
	(*OpLPushX)(nil),           // 14: patch.OpLPushX
	(*OpLRem)(nil),             // 15: patch.OpLRem
	(*OpLSet)(nil),             // 16: patch.OpLSet
	(*OpLTrim)(nil),            // 17: patch.OpLTrim
	(*OpRPop)(nil),             // 18: patch.OpRPop
	(*OpRPopLPush)(nil),        // 19: patch.OpRPopLPush
	(*OpRPush)(nil),            // 20: patch.OpRPush
	(*OpRPushX)(nil),           // 21: patch.OpRPushX
	(*OpSAdd)(nil),             // 22: patch.OpSAdd
	(*OpSRem)(nil),             // 23: patch.OpSRem
	(*OpSet)(nil),              // 24: patch.OpSet
	(*OpZAdd)(nil),             // 25: patch.OpZAdd
	(*OpZClear)(nil),           // 26: patch.OpZClear
	(*OpZIncrBy)(nil),          // 27: patch.OpZIncrBy
	(*OpZRem)(nil),             // 28: patch.OpZRem
	(*OpZRemRangeByRank)(nil),  // 29: patch.OpZRemRangeByRank
	(*OpZRemRangeByScore)(nil), // 30: patch.OpZRemRangeByScore
	(*OpRename)(nil),           // 31: patch.OpRename
	(*OpPersist)(nil),          // 32: patch.OpPersist
	(*OpZUnionStore)(nil),      // 33: patch.OpZUnionStore
	(*OpZInterStore)(nil),      // 34: patch.OpZInterStore
	(*OpRenameNX)(nil),         // 35: patch.OpRenameNX
}
var file_op_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_op_proto_init() }
func file_op_proto_init() {
	if File_op_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_op_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OpClear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OpDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OpExpire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OpExpireAt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OpHClear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OpHDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*OpHIncrBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*OpHIncrByFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*OpHSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*OpHMSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*OpLInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*OpLPop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*OpLPopRPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*OpLPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*OpLPushX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*OpLRem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*OpLSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*OpLTrim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*OpRPop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*OpRPopLPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*OpRPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*OpRPushX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*OpSAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*OpSRem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*OpSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*OpZAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*OpZClear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*OpZIncrBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*OpZRem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*OpZRemRangeByRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*OpZRemRangeByScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*OpRename); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*OpPersist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*OpZUnionStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*OpZInterStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*OpRenameNX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_op_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_proto_goTypes,
		DependencyIndexes: file_op_proto_depIdxs,
		MessageInfos:      file_op_proto_msgTypes,
	}.Build()
	File_op_proto = out.File
	file_op_proto_rawDesc = nil
	file_op_proto_goTypes = nil
	file_op_proto_depIdxs = nil
}
