name: ci
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: run unit tests
      run: go test
